name: ci
on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Aftman
        run: |
          brew install aftman/tap/aftman || {
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            brew install aftman/tap/aftman
          }
      - name: Install tools
        run: aftman install
      - name: Format check
        run: stylua --check .
      - name: Lint
        run: selene .
      - name: Build
        run: rojo build --output build/MidnightMall.rbxl
